server:
  port: 8080
  session-timeout: 60
  Name: test-name

application:
  name: dubbo-zipkin0

dubbo.trace:
  enabled: true
  connectTimeout: 60
  readTimeout: 60
  flushInterval: 0
  compressionEnabled: true
  applicationName: dubbo-zipkin0
  zipkinUrl: http://47.52.199.51:9411
